language: node_js
node_js: '6.10.0'
cache: yarn
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script:
  - yarn global add hexo-cli
  - hexo clean  
after_success:
  - git config --global user.name "Andy Chen" 
  - git config --global user.email "shinningstar1001@gmail.com"
  - sed -i'' "/^ *repo/s~github\.com~${Github_Token}@github.com~" _config.yml
  - hexo deploy
  - hexo algolia
