language: node_js
node_js: '6.10.0'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script:
  - npm install -g hexo-cli
  - npm install
  - hexo clean  
after_success:
  - git config user.name "Andy Chen" 
  - git config user.email "shinningstar1001@gmail.com"
  - sed -i'' "/^ *repo/s~github\.com~${Github_Token}@github.com~" _config.ym
  - hexo deploy
  - hexo algolia
